apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: demopods.k8s.dyc.com
spec:
  group: k8s.dyc.com
  names:
    kind: DemoPod
    listKind: DemoPodList
    plural: demopods
    singular: demopod
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      description: DemoPod is the Schema for the demopods API
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          description: DemoPodSpec defines the desired state of DemoPod 期望状态
          properties:
            replicas:
              type: integer
          required:
          - replicas
          type: object
        status:
          description: DemoPodStatus defines the observed state of DemoPod 运行状态
          properties:
            podNames:
              items:
                type: string
              type: array
            replicas:
              type: integer
          required:
          - podNames
          - replicas
          type: object
      type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
